name: docker-build-push

on:
  push:
    branches:
      # 监听推送到 master 分支
      - "main"
    # 监听以 v 开头的标签
    tags:
      - 'v*'
  pull_request:
    # 监听针对 master 分支的拉取请求
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      REGISTRY: 'docker.io'
      # 使用 GitHub 仓库名作为镜像名称，格式为 < 账户>/< 仓库>
      # IMAGE_NAME: ${{ github.generator }}
      IMAGE_NAME: aoian5173/chatweb

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          repository: 2926295173/NextChatWeb

      - name: Log in to Docker Hub
        # 仅在非 PR 事件中执行登录
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=ref,enable=true,priority=600,prefix=,suffix=,event=tag

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          # Docker 构建上下文为当前目录
          context: .
          # Dockerfile 路径
          file: Dockerfile
          # 如果不是 PR，推送镜像
          platforms: linux/amd64,linux/arm64
          
          push: ${{ github.event_name != 'pull_request' }}
          # 使用提取的标签推送镜像
          # tags: ${{ steps.meta.outputs.tags }}
          tags: aoian5173/chatweb:latest

          # 使用提取的标签作为镜像元数据
          labels: ${{ steps.meta.outputs.labels }}
